### PR TITLE
(fix): Jest Compatibility

### LINKED ISSUE #20: Jest v27 incompatible?
When running with jest@27.1.0 and ts-jest@27.0.5, the below error is thrown.

```shell
    TypeError: Cannot read property 'fn' of undefined

      at Object.mockRoomPositionConstructor (node_modules/screeps-jest/src/mocking.js:133:53)
      at TestEnvironment.setup (node_modules/screeps-jest/src/TestEnvironment.js:13:19)
      at TestScheduler.scheduleTests (node_modules/@jest/core/build/TestScheduler.js:333:13)
      at runJest (node_modules/@jest/core/build/runJest.js:387:19)
      at _run10000 (node_modules/@jest/core/build/cli/index.js:408:7)
      at runCLI (node_modules/@jest/core/build/cli/index.js:261:3)
```

### PR DESCRIPTION
**Pull request by patrickhousley**
Fixing compatibility with Jest v27+.

fixes #20

### CODE REVIEW

File: src/mocking.ts [hunk 1]
```diff
@@ -1,5 +1,5 @@
 import * as util from "util";
-import jestMock from "jest-mock";
+import * as jestMock from "jest-mock";
```
Comment (patrickhousley) [inline src/mocking.ts:2]: This is the primary change to make the project compatible.

File: src/mocking.spec.ts [hunk 2]
```diff
@@ -32,7 +32,7 @@ describe('mockInstanceOf', () => {
       build: () => OK
     });
     expect(mockCreep.body[1].type).toEqual(WORK);
-    expect(mockCreep.room.controller?.owner.username).toEqual('some-user');
+    expect(mockCreep.room.controller?.owner!.username).toEqual('some-user');
```
Comment (patrickhousley) [inline src/mocking.spec.ts:35]: This change was to satisfy a type-check error when building locally.

File: src/mocking.spec.ts [hunk 3]
```diff
@@ -288,7 +288,7 @@ describe('mockRoomPositionConstructor', () => {
     const roomName = 'W1N1';
 
     if ('RoomPosition' in global) {
-      delete global['RoomPosition'];
+      delete (global as any)['RoomPosition'];
```
Comment (patrickhousley) [inline src/mocking.spec.ts:291]: This change was to satisfy a type-check error when building locally.

File: src/mocking.spec.ts (hunk 2 above)
Comment (pyrodogg) [reply src/mocking.spec.ts:35]: Continuing the optional chaining for the potentially undefined property would be more accurate than asserting that it will not be undefined. `mockCreep.room.controller?.owner?.username`

File: package.json [hunk 4]
```diff
@@ -1,20 +1,20 @@
 {
   "name": "screeps-jest",
-  "version": "1.3.0",
+  "version": "2.0.0",
```
Comment (patrickhousley) [inline package.json:3]: Most Jest "plugins" (for the lack of a better word) follow the Jest versioning. Might be a good idea to do the same here and bump this to 27.0.0

Comment (eduter) [reply package.json:3]: Since it probably ony works with that specific major version, I think that makes sense.
